Aggiunta progettazione logica per tutte le basi di dati
SWEasabi/specifica-architetturale pull request #30
Opened 2023-07-20 13:37 UTC by romano001

2023-07-20 20:32 UTC, alessandro-massarenti requested changes
Dai un occhio ai commenti singoli

2023-07-20 20:32 UTC, alessandro-massarenti commented on src-doc/contenuti/specifica-basi-dati/img-sbd/anagrafica_logico.png
Ok, lo approvo ma non mi piace il verbo "è".
Dovrebbe essere sostantivato oppure usato il "misuratore-lampione" .

2023-07-20 20:32 UTC, alessandro-massarenti commented on src-doc/contenuti/specifica-basi-dati/img-sbd/logging_logico.png
Metterei i nomi in una lingua sola, come notato anche da  @SamuelPeron .

2023-07-20 20:32 UTC, alessandro-massarenti commented on src-doc/contenuti/specifica-basi-dati/img-sbd/anagrafica_logico.png
il doppio id lo metti per la cross reference?

In realtà se tu prendi "Lampione" hai già il campo "Misuratore" che è l'id del resto dell'oggetto.
Se invece prendo un misuratore da solo non mi serve a molto, quindi non serve il campo id su lampione e su sensore.

@pierobonluca01 , @casYy , @bonni1207 correggetemi se sbaglio.

2023-07-20 20:32 UTC, alessandro-massarenti commented on src-doc/contenuti/specifica-basi-dati/specifica-sistema-anagrafe.tex
> +\paragraph{Lampione} Diventando il Lampione un'entità a sé stante, vengono aggiunte una chiave primaria ed una chiave esterna che indica il Misuratore a cui fa riferimento.
Non sono sicuro sia corretta questa cosa.

2023-07-21 14:54 UTC, romano001 commented on src-doc/contenuti/specifica-basi-dati/specifica-sistema-anagrafe.tex
> +\paragraph{Lampione} Diventando il Lampione un'entità a sé stante, vengono aggiunte una chiave primaria ed una chiave esterna che indica il Misuratore a cui fa riferimento.
Cosa non ti convince? Mi sembra che sia questo quello che succede quando sostituisci una generalizzazione con una relazione

2023-07-21 14:56 UTC, romano001 commented on src-doc/contenuti/specifica-basi-dati/img-sbd/anagrafica_logico.png
> Ok, lo approvo ma non mi piace il verbo "è".
> Dovrebbe essere sostantivato oppure usato il "misuratore-lampione" .

Se hai qualche idea migliore diccela pure, altrimenti mettiamo "misuratore-lampione" e via. Abbiamo usato "è" perché piaceva a De Leoni

2023-07-21 14:56 UTC, romano001 commented on src-doc/contenuti/specifica-basi-dati/img-sbd/anagrafica_logico.png
> il doppio id lo metti per la cross reference?
> 
> In realtà se tu prendi "Lampione" hai già il campo "Misuratore" che è l'id del resto dell'oggetto. Se invece prendo un misuratore da solo non mi serve a molto, quindi non serve il campo id su lampione e su sensore.
> 
> @pierobonluca01 , @casYy , @bonni1207 correggetemi se sbaglio.

Il doppio id è dovuto alla ristrutturazione della generalizzazione

2023-07-21 14:57 UTC, romano001 commented on src-doc/contenuti/specifica-basi-dati/img-sbd/logging_logico.png
Ho scritto a Michele che sistemerà le immagini

2023-07-22 09:13 UTC, romano001 commented on src-doc/contenuti/specifica-basi-dati/img-sbd/anagrafica_logico.png
Il doppio id è stato eliminato, adesso è presente un solo id

2023-07-22 09:14 UTC, romano001 commented on src-doc/contenuti/specifica-basi-dati/img-sbd/logging_logico.png
I nomi ora sono tutti in una sola lingua

2023-07-23 16:25 UTC, alessandro-massarenti approved these changes

2023-07-23 16:25 UTC, alessandro-massarenti commented on src-doc/contenuti/specifica-basi-dati/img-sbd/logging_logico.png
ottimo

2023-07-23 16:35 UTC, merged